version: '3'
services:

  webapp:
    image: nginx:alpine
    volumes:
      - ./webapp:/usr/share/nginx/html
    ports:
      - "80:80"

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    networks:
      - app-network

  app:
    build: '.'
    ports:
      - '3000:3000'
    volumes:
      - ./api:/node-app
    depends_on:
      - mongo
    networks:
      - app-network

networks: 
  app-network:
    driver: bridge